"use strict";
let strings = [
	"cmon, fail fail fail, be a good boy.",
	"to eric: you're daddy cool",
	"everybody's smart... in their own ways",
	"OKKK as you wish mr dany coooooooow I wILL go and FIND IT, i'm going to smash you danny im going to find it",
	"to danny: im going to box your face",
	"im going to name this *stevengivesmeaccess*",
	"verybody is boomboomboomboom",
	"all that pasta... all on my pants",
	"steven is the goblin mentor",
	"cmon we are a lazy bunch of brats",
	"You run a 5k every day? That so easy.",
	"he got a new name, matrix danny",
	"thats why i call you a lazy shrug",
	"and then eric comes after me with his big red nose",
	"georgi porgi lets go get food",
	"everybody knows my word, my word is babaduke",
	"well, we know it works, because there are bugs",
	"because he's waiting for the pain test",
	"dont be a mean monster to me",
	"the ra farted on us",
	"Keshav talking to himself: OK, Undo the work you just did, Keshav",
	"You have a muscle",
	"someone stole my napkins",
	"I name my branch names like *DAH*",
	"danny is the hunky bro",
	"*exclaims* Lets go to Boston!!!! *under breath* and kick the shit out of him",
	"The networking team ... is dumb. I'm just kidding.",
	"I always talk shit.",
	"I miss Christmas",
	"my stomach is feeling bubbly bubbly, I am hungry, let's go bro",
	"When did you learn Hindi? 1992? Oh shit, i was born that year",
	"i stopped it but sometimes i do it",
	"I'm going to sue you! I'll take you to court and then I'll just say hi to you. The judge will be super pissed off.",
	"Give me money? I'll buy it.",
	"When i punch you in the face, you will cry.",
	"We're a bunch of noisy bunch of brats, but we're good.",
	"I'm a noisy chap",
	"God save humanity",
	"oh please, hes my bro",
	"if you touch him, ill be the most evilest person in the world",
	"There's this crazy guy called Keshav who talks... shit",
	"Get on the poll, in time i will learn to trust swathi.",
	"i love it when we screw up",
	"yayayadaaya that stupid thing aint failing *frog suit mario emoji*",
	"furball of knowledge",
	"i want to three finger, tap, tell your grand daddy that that happened",
	"i always fuck you",
	"the bang bang made the computer go ding dong",
	"lol , i can cry about the admin code test's, i have a lot of complains about that funky admin guy we got",
	"long live tomas roy",
	"the fur of knowledge",
	"brooo lol there is a channel to vent out sre oncall  issues , lets flood the channel with our dork messages lol",
	"i am going to say jajaja the sre oncall duty is really making my blood boil super high ''pufff  :volcano:",
	"our tom is the king",
	"it is a real pain in my prick man",
	"geheb is the master",
	"the spidy is hiding in the hood",
	"get the coffee shop babu",
	"lets go steven you rock. lets do the halleluia dance",
	"here is the baby boy keshav, jaja",
];

let num = Math.floor(Math.random() * strings.length)

document.write("<p> " + strings[num] + "</p>")
